services:
  # Backend - Django API
  - type: web
    name: soportix-backend
    runtime: python
    rootDir: helpdesk-backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn config.wsgi --log-file -
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://soportix-frontend.onrender.com"
      - key: RENDER_EXTERNAL_HOSTNAME
        value: "soportix-backend.onrender.com"
      - key: DB_ENGINE
        value: "django.db.backends.postgresql"
      - key: DB_NAME
        fromDatabase:
          name: soportix-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: soportix-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: soportix-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: soportix-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: soportix-db
          property: port

databases:
  - name: soportix-db
    databaseName: soportix
    user: soportix
    plan: free